version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/printerhub
    restart: unless-stopped
    networks:
      - printerhub-network

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: printerhub
    ports:
      - "5432:5432"
    networks:
      - printerhub-network
    restart: unless-stopped

networks:
  printerhub-network:
    driver: bridge

volumes:
  postgres_data: