services:
  printerhub-app:
    build:
      context: .
      dockerfile: Dockerfile.easypanel
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
      PGPORT: ${PGPORT}
    restart: unless-stopped
    depends_on:
      - printerhub-db
    networks:
      - printerhub-network

  printerhub-db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - printerhub-network
    restart: unless-stopped

networks:
  printerhub-network:
    driver: bridge

volumes:
  postgres_data: